### ISSUE TITLE
Add count fields.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/cirm-project#19]
Add a slide count and scan count field to experiment and specimen.
Add a scan count field to slide
Add triggers on scan and slide create to propagate counts to experiment and specimen and slide tables.

**Comment by svoinea** [comment]
The following columns were added:
- `Number of Scans` to the `Slide` table
- `Number of Scans` and `Number of Slides` to the `Specimen` table
- `Number of Scans` and `Number of Slides` to the `Experiment` table

The values were populated for the existing slides and scans.
Triggers were defined to update those values each time a scan or slide is added.
