### ISSUE TITLE
Update all link from piranha to the new host

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#20]
See the `HTTP URL` column on this record for example:

https://cirm.isrd.isi.edu/chaise/record/#1/Microscopy:Scan/ID=000c3184ab41812e18c2f0c250d059a00abbdce740fd1ddbf61d7670f43c62b7

We need to fix all of these links in the database so that they no longer point to piranha but instead to the files on the cirm server's hatrac service.

**Comment by robes** [comment]
This should be the first priority so that we can conclude the migration epic.

**Comment by svoinea** [comment]
The `cirm` and `cirm-staging` databases were updated such that the `HTTP URL` points now to the hatrac files location.
In the same time, the tiles generator script was updated to set the value for the `HTTP URL` column.

**Comment by robes** [comment]
Looks like your change was to make the URLs relative correct? Which is fine, I just want to be clear.
