### ISSUE TITLE
Updates to the Specimen schema

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#22]
Revised columns:
- ID
- Section Date
- Initials (should be FKR to User table)
- drop: Sample Name (review to detemine possible information loss)
- convert: Disambiguator
  - convert to integer
  - default to `0`
  - hide/ignore
- Comment
- drop: Tags
- Species (FKR)
- Age (FKR)
- Tissue (FKR)
- convert: `Gene`
  1. rename `Gene` to `Genes`
  2. convert string into a postgres array 
  3. annotate `Genes` column so that it is hidden/ignored during record create and edit
- add: `Gene` (_new_)
  1. make this a FK reference to the gene vocabulary table `code` column
  2. _copy_ the first element from the `Genes` array to fill this initial value
  3. drop: Specimen Identifier (review for information loss)

(*) We will _not_ add an association table for `specimen_gene` anymore. Instead we will use the `Genes` array above in the future for multiple gene entry. For now, we will allow only a single `Gene` to be entered.

Trigger:
- We will want a trigger to generate the ID based on the user selection of terms and the time stamp and user initials, rather than doing this in the javascript client. If the ID is new, it does not need a disambiguator. If the ID exists, then we should append it to the ID as "base ID`-`max(disambiguator)+1"

**Comment by svoinea** [comment]
Done.
