### ISSUE TITLE
Updates to the Experiment schema

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#23]
Revised columns:
- ID
- Experiment Date
- drop: Experiment Description (but we need to make sure this data is reflected in the other fields so we are not losing information)
- Initials (should be FKR to User table)
- drop: Disambiguator
- Comment
- drop: Tags
- Experiment Type
- convert: Probe*

(*) The Probe column is a concatenated string of probe names. The probe names are already in a domain table. We need to add an association table between `Experiment <- A -> Probe` and then populate the association table according to the tokens in Probe.

Trigger:
- We will want a trigger to generate the ID based on the user selection of terms and the time stamp and user initials, rather than doing this in the javascript client.

**Comment by robes** [comment]
@svoinea this is done, right?

**Comment by svoinea** [comment]
Yes.
