### ISSUE TITLE
Updates to the Slide schema

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#24]
Keep all columns except:
- drop: "Rev." column. It has never been used.

Trigger:
- We may need a trigger to generate the "Seq." (sequence) and ID columns. We should expect that for data entry, the user will use the multiple entry mode of the record edit app. The ID should be generated based on the Specimen ID (FKR) and the Seq columns. The user should be able to enter a sequence number for the first slide and the sequence should then be generated starting at that first entered sequence number. Or if the user is adding more slides for a specimen that already has some slides, the trigger should start from the last Seq.+1 and so on.

**Comment by svoinea** [comment]
Done.
