### ISSUE TITLE
Updates to migrate Scan table to `image` table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#25]
Change the following columns (\* if not mentioned in this list, leave the column as is):
- change "ID": we should convert this to be '<Slide ID>-Serial'
- we would like to drop "Original Filename" if possible: we may need to review this because we would have to change the file names in hatrac. We don't need to name files by their checksums anymore now that we can push them into hatrac rather than onto the file system
- drop "GO Endpoint"
- drop "GO Path"
- drop "Filename"
- annotate "Thumbnail" so that it displays the thumbnail image
- drop Zoomify
- drop Tags
- annotate "DZI": so that it links to the viewer (this may not be necessary since the viewer should probably be the app link anyway)
- hide 'czi2dzi': this should not be visible to the end user

Trigger: add a trigger that generates the Scan.ID as described above for all future files that are added.

**Comment by robes** [comment]
We decided that we should migrate our `Scan` table to the `image` table like we used on RBK.

| Scan | RBK image | CIRM image | Comments |
| --- | --- | --- | --- |
| ID | - | - | no direct mapping |
| - | id | - | no direct mapping |
| Slide ID | slide_id | slide_id | same; should be FK on slide(id) |
| - | - | seq | a sequence ID, generated by trigger; (slide_id, seq) = PK |
| Original Filename | - | original_filename | preserve for legacy data |
| GO Endpoint | - | - | drop |
| GO Path | - | - | drop |
| HTTP URL | - | identifier | same |
| Filename | filename | filename | same |
| File Size | bytes | bytes | same |
| Thumbnail | - | thumbnail | same |
| File Date | - | created_date | change name; value same |
| - | accession_number | accession_number | need to populate it with "slide_id-seq" |
| - | submitted | submitted | can be set by DEFAULT = 'now()' |
| - | mime_type | mime_type | same |
| - | description | description | same |
| - | submitter | submitter | should turn into FK on a user table |
| - | tissue | tissue | from Scan.Slide.Specimen.Tissue |
| - | gender | gender | no legacy data |
| - | age_stage | age_stage | from Scan.Slide.Specimen.Age |
| - | specimen_fixation | specimen_fixation | no legacy data |
| - | embedding_medium | embedding_medium | no legacy data |
| - | staining_protocol | staining_protocol | from Scan.Slide.Experiment.Experiment Type |
| - | status | status | no legacy data |

Then there are other column in `Scan` such as `Microscope`, `Channel Name`, etc. We should simply preserve these as columns in the new CIRM `image` table.

**Comment by svoinea** [comment]
The current definition of the `Scan` table:

```
microscopy=# \d "Scan"
                                       Table "Microscopy.Scan"
         Column         |         Type          |                      Modifiers                      
------------------------+-----------------------+-----------------------------------------------------
 slide_id               | character varying(37) | not null
 filename               | text                  | 
 HTTP URL               | text                  | 
 bytes                  | bigint                | 
 Thumbnail              | text                  | 
 Comment                | text                  | 
 Microscope             | text                  | 
 Camera                 | text                  | 
 Objective              | text                  | 
 Exposure Time          | text                  | 
 Channels               | integer               | 
 Channel Name           | text                  | 
 Contrast Method        | text                  | 
 Magnification          | text                  | 
 Light Source Intensity | text                  | 
 Image Size             | text                  | 
 Scaling (per pixel)    | text                  | 
 DZI                    | text                  | 
 czi2dzi                | text                  | 
 File Date              | date                  | default now()
 Acquisition Date       | date                  | 
 id                     | integer               | not null default nextval('"Scan_id_seq"'::regclass)
 species                | text                  | 
 age                    | text                  | 
 gene                   | text                  | 
 checksum               | text                  | 
 accession_number       | text                  | 
 doi                    | text                  | 
 ark                    | text                  | 
 mime_type              | text                  | 
 description            | text                  | 
 submitter              | text                  | default 'anonymous'::text
 submitted              | date                  | 
 public_release_date    | date                  | 
 tissue                 | text                  | 
 gender                 | text                  | 
 age_stage              | text                  | 
 specimen_fixation      | text                  | 
 embedding_medium       | text                  | 
 staining_protocol      | text                  | 
 resolution             | text                  | 
 uri                    | text                  | 
 status                 | text                  | 
 last_modified          | date                  | not null default now()
Indexes:
    "Scan_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "Scan_Slide ID_fkey" FOREIGN KEY (slide_id) REFERENCES "Slide"("ID")
    "Scan_age_stage_fkey" FOREIGN KEY (age_stage) REFERENCES age_stage(term)
    "Scan_embedding_medium_fkey" FOREIGN KEY (embedding_medium) REFERENCES embedding_medium(term)
    "Scan_gender_fkey" FOREIGN KEY (gender) REFERENCES gender(term)
    "Scan_specimen_fixation_fkey" FOREIGN KEY (specimen_fixation) REFERENCES specimen_fixation(term)
    "Scan_staining_protocol_fkey" FOREIGN KEY (staining_protocol) REFERENCES staining_protocol(term)
    "Scan_status_fkey" FOREIGN KEY (status) REFERENCES image_status(term)
    "Scan_tissue_fkey" FOREIGN KEY (tissue) REFERENCES tissue(term)
Referenced by:
    TABLE "annotation" CONSTRAINT "annotation_image_id_fkey" FOREIGN KEY (image_id) REFERENCES "Scan"(id)
Triggers:
    scan_trigger_after AFTER INSERT OR UPDATE ON "Scan" FOR EACH ROW EXECUTE PROCEDURE scan_trigger_after()
    scan_trigger_before BEFORE INSERT OR UPDATE ON "Scan" FOR EACH ROW EXECUTE PROCEDURE scan_trigger_before()

microscopy=# 
```
