### ISSUE TITLE
Configure navbar menus

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#27]
- Search: to the chaise/search app
- Create (under here go record edit links)
  - Specimen
  - Experiment
  - Slide
- Data
  - submenus to take them to the recordset app for specific filters (tbd)
- Vocabulary
  - links to the various domain tables that we have in the schema (e.g., Gene, Probe,...)
- Admin
  - Specimen Label Printer
    - submenu items
  - Slide Label Printer
    - submenu items

**Comment by svoinea** [comment]
This is done, less the `Admin` menu, that needs implementation for the `printer` requests.

**Comment by svoinea** [comment]
The `Admin` menu was added with commands to check the connection and the status of the printers.
