### ISSUE TITLE
Print from Specimen and Slide records

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#29]
We should be able to add a link to invoke the printer from both the Specimen and Slide record pages (this may extend the columns of both table).

Caveat 1: the link for printing a Slide will only work if the Specimen ID has been set.

Caveat 2: we need to review the rest handler for printer because it might take a POST method. It might also expect the json body of the record. We may need to change the handler to 1. use the GET method and 2. simply take a Slide/Specimen ID and do a lookup in ERMrest itself to get the rest of the details to send to the printer api. **TBD**

**Comment by svoinea** [comment]
This is currently implemented by using a `GET` request for the `Print Label` link.

**Comment by robes** [comment]
@svoinea can you explore some styling on the "Print Label" link with markdown etc that would make it look like a button?

**Comment by svoinea** [comment]
@robes Added the `{download .btn .btn-primary target=_blank}` CSS styling.
