### ISSUE TITLE
Update iobox configuration per revised data model

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#30]
As we make the revisions to the CIRM model we will need to review and probably update the iobox configuration. For instance, will the ERMrest step still send the same attributes? I think those are probably going to change.

Note: we should get away from using the checksums for filenames. That was necessary before when we stored on the file system for uniqueness (without additional roundtrips to the database involved). We don't need this anymore and we can preserve the original filename in the post to hatrac.

**Comment by svoinea** [comment]
An updated version of the configuration file was already created and tested on `cirm-dev`.
It refers the new columns names of the `Scan` table.
The file is uploaded now in `hatrac` having the name composed from the concatenation of the `slide_id` and the `Disambiguator`, with the `-` separator.
