### ISSUE TITLE
Search on Scan table by default

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#34]
Scan table columns to be visible in the chaise/search:
- Thumbnail
- Image Identifier
- Species (Specimen)
- Tissue (Specimen)
- Gene (Specimen)
- Age (Specimen.Age_Value + `' '` + Speciment.Age_Unit)
- Submitted By
- Acquisition Date

These should be visible:
- in the face list
- and in the table of results
- except for thumbnail

**Comment by svoinea** [comment]
This is done. In the facets list I have added also the attributes for the channels and comment.
