### ISSUE TITLE
Annotations for 'Compact' context on Scan table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#35]
For the `Scan` table, in the `Compact` context, the `VisibleColumns` should be:
- Thumbnail
- Image Identifier
- Species (Specimen)
- Tissue (Specimen)
- Gene (Specimen)
- Age (Specimen.Age_Value + ' ' + Speciment.Age_Unit)
- Submitted By
- Acquisition Date

And use markdown to generate the thumbnail and links. See:
https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide

**Comment by svoinea** [comment]
This is done.
