### ISSUE TITLE
Annotations for Experiment table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#37]
Sub tasks:
- [x] annotate for search
- [x] annotate for record

On Search, show the following columns:
- ID
- Initials
- Experiment Date
- Experiment Type
- Probe
- Comment

On Record page:
- the same set of columns in order should appear.

**Comment by robes** [comment]
Add `generated` and `immutable` annotations to the `id`.

Hide `disambiguator` from all views including entry/edit. So you might be able to see if there is a `default` context.

**Comment by svoinea** [comment]
This is done. Currently, it seems that the `generated` and `immutable` annotations are not yet implemented.

**Comment by svoinea** [comment]
This is done now by replacing the `generated` annotation with the `ignore` one. In that way, the auto-generated columns will not be visible.
