### ISSUE TITLE
Propagate metadata from Specimen and Slide to Scans

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#40]
Since the Scan table now has the FKR columns from the rbk.image schema, make sure we accurately propagate the related terms from the associated Specimen and Slide to the Scans.
- [x] we need a one time migration of all existing data
- [x] we need a trigger or other mechanism so that when new scans are added we automatically populate these fields.

**Comment by svoinea** [comment]
The scans are added through the `iobox`.
A trigger was already defined to inherit the related terms from the specimen and experiment it belongs to.
