### ISSUE TITLE
Annotations on Scan table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#42]
- [x] title should be displayed based on the `accession` column
  - I believe this is configured with the `row_name` context of the table display annotation
  - see https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-table-display
- [x] columns should be displayed in "Title Case"
  - this can be configured with an annotation at the Schema level and inherited by all model elements under it
  - see the `name_style` property of display annotation
  - here https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2015-display
- [x] apply markdown on the vocabulary columns so that they appear in bubbles
  - both RBK and FaceBase are using it so they can provide example on how to do it
- [x] display thumbnails using markdown template
- [x] set the visible columns annotation
  - see https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-visible-columns

Column order for the `detailed` context should be:
- thumbnail
  - should be annotated as image and links to viewer app
- HTTP URL
  - should be annotated as a download link
- bytes
- Acquisition Date
- Submitter
- species
- tissue
- age
- gene
- gender
- description (but don't populate this with the accession id)
- Image Size
- Objective
- Channels
- Channel Name
- Contrast Method
- Light Source Intensity
- Exposure Time
- resolution
- Scaling

**Comment by svoinea** [comment]
This is done.
