### ISSUE TITLE
2d viewer buttons not working (on dev)

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#43]
The buttons like zoom in/out, etc do not work on the 2d image viewer.

@svoinea thinks this might be because the images are loaded from a different host. We should review this issue only after we update to the staging server.

**Comment by svoinea** [comment]
A version is currently available on `cirm-staging` having the images loaded in the same host.

**Comment by robes** [comment]
I tried all the basic operations I coudl think of. seems to be working.
