### ISSUE TITLE
Use different 'generic' thumbnail

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#44]
When the data has no thumbnail, you are currently using the double-helix (dna/genetics) image. We really don't have a default thumbnail for this, but I think this one would be closer.

https://www.facebase.org/hatrac/facebase/thumbnail/fb1/generic_mixed.png:A6V7BTIBXBF2M7N35HD2S5DTQM

Can you please switch to this one? thx

**Comment by svoinea** [comment]
Done on cirm-dev.
