### ISSUE TITLE
Scan Record

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/cirm-project#48]
- In  Resolution and Scaling, we should round these numbers to a smaller number of digits.  Right now we have something like: 2.1952155277572531E-07, 2.1952155277572531E-07
- The field Http URL, should be relabeled to something like "Download CZI file"
- It is not clear from the scan record that you click the thumbnail to look at the image.  We should make this clearer.

**Comment by robes** [comment]
these were done
