### ISSUE TITLE
Add dashboard

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#49]
Add a dashboard similar to https://dev.rebuildingakidney.org/chaise/recordset/#2/Common:RBK_Resources

But we will probably need to create a materialized view because CIRM has 1000s of scans and count(*) will do a 'full table scan' each time we query (ie, view) the dashboard.

This adds some complexity because then we will need triggers for view maintenance.

Let's start by adding it as a (non-materialized) view and see how bad it performs before making it materialized.

**Comment by svoinea** [comment]
Added the view and the dashboard is currently accessible through the https://cirm-dev.isrd.isi.edu/chaise/recordset/#1/Microscopy:CIRM_Resources link.

**Comment by robes** [comment]
nice. it loaded really fast for me. is it materialized?

**Comment by svoinea** [comment]
No. I don't think it is necessary, as the query is very simple using just the `count()` and `max()` functions.
I have just added the annotation that makes the first column a link to the `/chaise/search` pages of those tables.
