### ISSUE TITLE
Set up groups and access control lists

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#51]
So that the 2d viewer will allow annotations on images for right groups of users.

**Comment by svoinea** [comment]
The code already implements the `chaise-config` option `userGroups`:

```
userGroups: {
        users: 'https://auth.globus.org/...',
        annotators: 'https://auth.globus.org/...',
        curators: 'https://auth.globus.org/...'
}
```

I think the `users` group should be `cirm-usc` and the manager/administrator of that group should create subgroups for the `annotators` and `curators`.
