### ISSUE TITLE
Use table display annotation on associated genes

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#52]
See https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-table-display

And the markdown guide here:
https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide#9-to-render-a-block-as-vocabulary

Apply to the `Specimen Gene` table. Like here:

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Specimen/ID=20160915-Gdf15het48hGA22-GA-0

We want a formatted display like this:

https://dev.facebase.org/data/record/#1/legacy:dataset/id=14055

**Comment by svoinea** [comment]
Added the following annotation:

```
('Microscopy', 'specimen_gene', 'tag:isrd.isi.edu,2016:table-display', 
'{
    "compact": {"row_markdown_pattern":"**{{Gene ID}}**{.vocab}","separator_markdown":" "}
}')
```
