### ISSUE TITLE
Do not display "Print Label" link when slide is not assigned to an experiment

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#53]
The "Print Label" should not even appear on those slides. There is a conditional check feature (check for null of a column value) and then do not produce the markdown.

Here's an example of a Specimen that has one slide that has a correct Print Label and one that should not have it.

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Specimen/ID=20160801-mKDAWT3dsham-JL-0

**Comment by svoinea** [comment]
The annotation for `check NULL` was added.
