### ISSUE TITLE
Name and store files based on the Slide ID

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#54]
In hatrac.

This might be an IOBox configuration change only.

**Comment by svoinea** [comment]
For now, in the `Scan` table, I have removed from the (original) `filename` the prefix `httppurl.orgusc-cirmslideid=`.
The `filename` is the URI text displayed when you download the file.

**Comment by svoinea** [comment]
This issue is correlated with the issue #30
