### ISSUE TITLE
Fix encoding in title (row_name) and possibly in other annotations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#55]
Note here that `&` gets URL encoded.

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Experiment/ID=20160915-H%26ENone-GA-0

Here's the markdown guide for escaping. This should point to the solution.

https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide#disable-escaping

**Comment by svoinea** [comment]
@robes I tried the solutions described in the documentation, but nether worked:

```
('Microscopy', 'Experiment', 'tag:isrd.isi.edu,2016:table-display', '{
    "row_name" :{"row_markdown_pattern":"{{{ID}}}"}
}')
```

or:

```
('Microscopy', 'Experiment', 'tag:isrd.isi.edu,2016:table-display', '{
    "row_name" :{"row_markdown_pattern":"{{&ID}}"}
}')
```

I saw that the `{{{name}}}` solution is used in `Facebase`.

**Comment by robes** [comment]
Did the tripple-{ work?

I have heard of that.

**Comment by svoinea** [comment]
Neither of them worked so far.

**Comment by karlcz** [comment]
Have you tried the row_markdown_pattern `{{#escape}}{{{ID}}}{{/escape}}` which will apply markdown escaping to any special characters, so the markdown renderer won't interpret them as markdown while generating an HTML fragment?

I'm not sure this is necessary for a bare `&` but it might be worth a shot...

**Comment by svoinea** [comment]
The issue was fixed meanwhile, and the title is displayed escaped.
