### ISSUE TITLE
Specimen 'identifier' and 'sample name'

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#57]
We don't need the `specimen identifier` and `sample name` attributes, as far as I can tell.

**Comment by svoinea** [comment]
The `sample name` was already removed.
@robes Currently there is a large number of distinct text values for the `Specimen Identifier` (549).
Some examples:

```
1026KO
11-17'3d-IRI
13-15min-4d-IRI
1dose48hrCollection
28dGA57
8wkKO2
Hom11
```

They are free text entered by the user, probably meaningful. Therefore, I'm not sure that we can supply a solution to auto-generate them.

**Comment by robes** [comment]
But we won't allow 'meaningful' free text anymore. We probably shouldn't drop these columns from the db yet. We should extract what we can. Let's just hide them by using the `visible columns` annotation.

**Comment by svoinea** [comment]
For the new `Specimen` entities, the `Specimen Identifier` will be set to the empty string and it will not be any more exposed to the user.
