### ISSUE TITLE
cirm-staging new recipe

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/cirm-project#6]
- Uses hosted NFS

**Comment by svoinea** [comment]
`cirm-staging` was created with 500GB for `cirm-staging-data.img`.
The VM was created with `NEW_DATA=true`.

**Comment by svoinea** [comment]
Notes were added in the Wiki page https://github.com/informatics-isi-edu/microscopy/wiki/cirm-staging

In case of a new install, in the `/var/www/html/webcli/js/app.js` file, the `box.example.org` and `slide.example.org` values need to be replaced with the ones from the `ermrest_config.json` of the `cirm-staging` recipe.

Most likely, these will be part of the recipe.

**Comment by karlcz** [comment]
The recipe has been updated to track upstream webauthn changes. 

Long-term credentials need to be recreated:
- We need to use an iobox agent account _not_ a human developer's account for this session
- Session table in `webauthn` DB
- Cookie name `webauthn` instead of `ermrest`

**Comment by karlcz** [comment]
A new software-lib function `cirm_webcli_customize` has been added to patch the webcli/js/app.js with site customization after the `microscopy_webcli_install` step is complete. This is wired into the 50-software-install.sh script.

**Comment by svoinea** [comment]
The `cirm-staging` recipe was applied and validated by the CIRM people who have already uploaded about 100 files.
A similar recipe was developed for the `cirm` production, and soon `cirm-staging` will be migrated to the `cirm` production.
