### ISSUE TITLE
Order of incoming foreign keys

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#60]
Let's put the vocabulary terms like `specimen gene` ahead of incoming links like `slides`.

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Specimen/ID=20160915-Gdf15het48hGA22-GA-0

There's an annotation for visible foreign keys.

https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-visible-foreign-keys

I believe you use that annotation to control not only visibility but ordering too.

**Comment by svoinea** [comment]
This is already done by using the `tag:isrd.isi.edu,2016:visible-foreign-keys` annotation.
