### ISSUE TITLE
Make 'age' facet visible by default when searching on Scans table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#61]
Could things actually:

- [x] make 'age' facet visible (probably means ordering it to the 'top' in this search interface)
- [x] also, the values of the 'age' facet should be sorted in a meaningful way (i.e., we should use a sort key so that it goes days... weeks... years...), but currently, they are sorted by a lexical order (days might be mingled with weeks because of the numeric components of the ages)

**Comment by svoinea** [comment]
The annotation `top` was added for the `Age` column of the `Specimen` and `Scan` tables.
The numeric `age_rank` column was added to the `Specimen` and `Scan` tables to make the sort of the `Age` column adequately.
