### ISSUE TITLE
cirm-staging test printer service

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/cirm-project#7]
Test the printer service connecting to cirm-staging

**Comment by svoinea** [comment]
The connection was tested with the current `cirm-staging` and was successfully.
Updated with this occasion the microscopy code with configuration to be specific for Centos 7 and Python 2.7, as the existence one was for Centos 6 and Python 2.6.

**Comment by svoinea** [comment]
This should be re-tested once the new CIRM production iobox will be available.

**Comment by svoinea** [comment]
CIRM people have tested that they can print labels.
