### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/cirm-project#70]
On Experiment record page

- Make links on Number of Slides/Scans to record set of records or scans
- In nested slide table, make column heading "Id" -. "Slide ID"
- In nested slide table, made Slide ID column link to slide, disable select on entire row
- Should Print Label button be visible to me?
- Tool tips?

On SCAN record, its not obvious that you click on the thumbnail to get the image browser.  Would it be possible to either put some text in there to indicate this, or put in a attribute that is the image viewer?
- Is there anything we can do to format the display of the resolution and scaling to limit the number of digits displayed?
- Why is the display of the gene name on the scan record different then that on the specimen record.  I would make them the same (the link?)

On Specimen page, 
- why is the Age different then the Gene and other fields?  Would we want to link on age.  
- Again, I find the use of selections on the nested slide table inconsistent.  I would rename the ID column and provide a link on that.  We should discuss this, but I think the mix of some columns have links and others don't but if you click over them it takes you to the entry is kind of confusing

**Comment by svoinea** [comment]
When you click a Specimen or Experiment id, the record page displays now in the compact context the related scans and slides.
The "ID" columns are now displayed using their tables names as a prefix.
On SCAN record, some text indicates now how to get the viewer or download the `czi` file.
The resolution and scaling columns are now hidden.
The `Scan.gene` column is now a link to the vocabulary table.
For the Specimen table, currently just the `Age Unit` column is a reference to a vocabulary table. The `Age` column is composed by concatenating a numeric value with the age unit.
