### ISSUE TITLE
Changes to Scan columns

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#71]
For column `Scan.Thumbnail`:
- add a `comment` to the schema: "Click the thumbnail to open the full resolution image in the online viewer"

For column `Scan.Http Url`:
- annotate its `display name` to be: "Download Link"
- add a `comment` to the schema: "Click the link to download the CZI file"

I would hide these columns:
- Image Size: because its wrong, the metadata is wrong here
- Resolution: if we can't fix the display
- Scaling: if we can't fix the display

**Comment by robes** [comment]
`COMMENT ON COLUMN table.column IS 'text here...';`

https://www.postgresql.org/docs/9.1/static/sql-comment.html

**Comment by svoinea** [comment]
The comments were already added in the database.
The `Scan.HTTP URL` column is now displayed as `Download Link`.
The `Scan` columns `Image Size`, `Resolution` and `Scaling` are now hidden.
