### ISSUE TITLE
Changes to Specimen Genes and Experiment Probes

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#73]
First, we can annotate these columns `immutable`:
- `Specimen.Gene`
- `Experiment.Probe`

Then we can annotate the associated tables:
- `Specimen_Gene` and
- `Experiment_Probe`
with the markdown table display annotation so that they appear as vocabulary term "bubbles" as we have done on FaceBase.

See this for example:

https://www.facebase.org/data/record/#1/legacy:dataset/id=14053

Look at the FaceBase schema if you want the exact annotation used.

**Comment by svoinea** [comment]
The above mentioned columns were annotated as `immutable`.
The `specimen_gene` and `experiment_probe` tables were annotated as vocabulary term "bubbles".
