### ISSUE TITLE
Annotation tweaks

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#74]
Specimen:
- Detail context:
  - Since we have linking on FKeys, let's drop the markdown on the column display (for instance, the "Age" column uses the markdown)
  - Hide "Specimen ID" since its used in the row name / title already

Slide:
- Detail context
  - Hide "Slide ID"
- all context
  - rename "Specimen Id" => "Specimen"
  - "Experiment Id" => "Experiment"

Experiment:
- Detail context
  - hide "Experiment ID"

Scan:
- all context
  - renamed "Accession Number" => "Scan ID"
- Detail context
  - renamed "Slide ID" => "Slide"

**Comment by svoinea** [comment]
Added the adequate annotations for hiding or displaying the above columns.
