### ISSUE TITLE
delete does not work due to FKey constraints

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#76]
For example,
- create Experiment
- add Probes
- go back to Experiment
- try to delete

> Error 409 Conflict The request conflicts with the state of the server. update or delete on table "Experiment" violates foreign key constraint "experiment_probe_Experiment ID_fkey" on table "experiment_probe" DETAIL: Key (ID)=(20161118-TRICCDC1-RES) is still referenced from table "experiment_probe". 

When deleting Experiment and Specimen entities, it should have a cascading delete to the respective "Experiment Probe" and "Specimen Gene" entities.

**Comment by svoinea** [comment]
Added `ON DELETE CASCADE` to the `"specimen_gene"."Specimen ID"` and `"experiment_probe"."Experiment ID"` foreign keys.
