### ISSUE TITLE
visible foreign keys annotations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#77]
A couple similar changes:
- For `Probe` table:
  - include only `Experiment Probe`s not `Experiment`s
- For `Gene` table:
  - include only `Specimen Gene`s not `Specimen`s

Otherwise you get two overlapping tables of Experiments or Specimens, respectively.

**Comment by svoinea** [comment]
Added the adequate annotations for the `probe` and `gene` tables.
