### ISSUE TITLE
Bring back 'Specimen Identifier'

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#80]
And check whether we were doing anything special with it -- like using it in the formation of the 'ID'. But my guess is we were _not_ and it was probably just a plain text entry field.

**Comment by svoinea** [comment]
The `Specimen Identifier` is back. It was just hidden as for new specimens we were just generating an empty string for it.
We allow the user to specify a free text for it. It is used in generating the `sample_name` which at its turn is part of the `ID` as well as of the `Label`.
As it seems to be useful for them, I have included it in the summary search page as well as in the facets to be searched. It is now present also in all the other contexts.
