### ISSUE TITLE
Annotate tables with the `row_order`

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#82]
These tables need the `row_order` annotation.

- Specimen
- Experiment
- Scan

They should be sorted by their various `... Date` fields, preferably in `desc` order.

See this for reference:

https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-table-display

**Comment by svoinea** [comment]
The `row_order` annotation in the `desc` order was added for the various `... Date` fields of the above three mentioned tables.
