### ISSUE TITLE
Add links to Plot views

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#84]
Add a new top level menu drop down with menu items to link to various plots.

* `Dashboard`
  * `Scans by Date` => `/chaise/search/#1/Microscopy:Scan?layout=plot&plot=(type:histogram,x:Acquisition%20Date)&page=1`
  * `Scans by Species` => `/chaise/search/#1/Microscopy:Scan?layout=plot&plot=(type:histogram,x:species)&page=1`
  * `Scans by Probe` => `/chaise/search/#1/Microscopy:Scan?layout=plot&plot=(type:scatter,x:Acquisition Date,y:probe)&page=1`
  * `Scans by Gene` => `/chaise/search/#1/Microscopy:Scan?layout=plot&plot=(type:scatter,x:Acquisition Date,y:gene)&page=1`

**Comment by svoinea** [comment]
@robes I have applied them on `cirm-dev` as well as on `cirm-staging`.
While on `cirm-dev` the charts are displayed, on `cirm-staging` I can see just `Use the dropdown menu(s) to select attributes for use as plot coordinates.`

**Comment by robes** [comment]
Looks good. The cirm-staging wont' work until we update the code, so that's fine/expected.
