### ISSUE TITLE
Can't navigate to Slide from Scan record

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#85]
https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Scan/id=2969

Shouldn't the `Slide` column be a URL? I thought it was before.

**Comment by svoinea** [comment]
I have added in the script that converts the CIRM database from the old format to the new format, the `tag:isrd.isi.edu,2016:column-display` annotation to the `Scan:slide_id` column, such that it will be displayed as an URL. That script will be run on `cirm-www`.
Manually, I have added that annotation on `cirm-dev` and `cirm-staging` VMs that have already the CIRM database in the new format.
