### ISSUE TITLE
January Pre-release check

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#86]
A list of issues I'm seeing in the pre-release check.

- [x] empty nested tables should not be _shown_ by default. they should be hidden by default.
- [x] from Experiment, clicking Add on a probe should take you to a record edit page to add the associative entity _not_ the actual probe entity.
- [x] from Specimen, clicking Add on a gene should take you to a record edit page to add the associative entity _not_ the actual gene entity.
- [x] the edit buttons (such as in the Actions column of nested tables) for 'Scan' should be disabled.
- [x] the 'Add' link for 'Scan' (such as when it appears as a nested table) should be disabled/hidden
- [x] under the "Admin" menu of the navbar the "Specimen" and "Slide" menu items should be "Box Label Printer" and "Slide Label Printer".
- [x] _if possible_ I would prefer that the navbar menu items open the page in the _current_ window rather than in a new window. It really clutters up the browser with lots of tabs.
- [x] _undo_ the above request or if possible only undo it for any reference to the chaise/search page because chaise/search will not refresh itself when the URL fragment changes. therefore, the URL changes according to the navbar _but_ the page doesn't change. So that's not going to work.
- [x] do not show the `probe` column (remove from visible columns list) in the `compact` view of the `Experiment` table
- [x] do not show the `gene` column (remove from the visible columns list) in the `compact` view of the `Specimen` table
- [x] drop the markdown annotations for all vocabulary columns (see `Experiment`, `Specimen`, and `Scan` tables) -- no more "chiclet" bubbles around the values
- [x] instead, if/when you add these columns to visible columns list of the respective tables, use the _constraint name_ of the foreign key rather than the _column name_ this way the chaise/record and chaise/recordset pages will automatically display them as URLs that link to the record pages for those terms.

**Comment by robes** [comment]
@svoinea some additional minor changes

- [x] for all vocabulary tables (probe, gene, etc.) the 'visible columns' should be only `code` and `term`. (that will hide the `id` column)
  - for e.g., https://cirm-staging.isrd.isi.edu/chaise/record/#1/Microscopy:gene/id=14
- [x] don't show `genes` column in the `compact` context of `specimen`
  - for e.g., https://cirm-staging.isrd.isi.edu/chaise/record/#1/Microscopy:gene/id=14
- [x] don't show `probes` column in the `compact` context of `experiment`
  - for e.g., https://cirm-staging.isrd.isi.edu/chaise/record/#1/Microscopy:experiment_type/id=7

**Comment by robes** [comment]
@svoinea why is there a nested table for "Experiment Type" as the bottom of the record page for an "Experiment Type"?

**Comment by robes** [comment]
@svoinea  can we fix this too?

- [x] the `specimen_gene` table should use the to/from name annotation so that from the Specimen table its display name is `Genes` and from the Gene table its display name is `Specimens`
  - see https://cirm-staging.isrd.isi.edu/chaise/record/#1/Microscopy:gene/id=87
  - and https://cirm-staging.isrd.isi.edu/chaise/record/#1/Microscopy:Specimen/ID=20160608-mO7PGfra3_18B-JJG-0
- [x] the `experiment_probe` table should use the to/from name annotation so that from the Experiment table its display name is `Probes` and from the Probe table its display name is `Experiments`
  - see https://cirm-staging.isrd.isi.edu/chaise/record/#1/Microscopy:Experiment/ID=20160804-IHCGfra3Tuj1-JJG-0
  - and https://cirm-staging.isrd.isi.edu/chaise/record/#1/Microscopy:probe/id=236

See the `foreign key` annotation spec for details on how to do this.

https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-foreign-key

**Comment by svoinea** [comment]
@robes The vocabulary tables have a FK to themselves (the `superclass_id` column). The nested tables appeared when the annotation `tag:isrd.isi.edu,2016:visible-foreign-keys` was missing.
I have added it for all the vocabulary tables, such that it excludes the reference to themselves.

**Comment by svoinea** [comment]
The `cirm-staging` was re-deployed with the latest tags and it is ready for review.

**Comment by robes** [comment]
looks good. we just need to confirm that it works on MS IE before pushing to staging.
