### ISSUE TITLE
Propagate experiment information to the Scans

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#88]
Propagate to scans table like we are doing with Tissue, etc. 
- [ ] experiment type
- [ ] probes

Also these should be searchable.
E.g., should be able to search on "H&E".

**Comment by svoinea** [comment]
@robes A version is already deployed on `cirm-staging`.
The `Experiment Type` facet is preselected in the search view.
The `Experiment Type` and `Probes` values are displayed in the detailed view.
