### ISSUE TITLE
Paging is broken on Scan table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#89]
Go here

https://cirm-staging.isrd.isi.edu/chaise/recordset/#1/Microscopy:Experiment/ID=20160913-H%26ENone-JAM-0/(ID)=(Microscopy:Scan:Experiment%20ID)@sort(Acquisition%20Date,id)?limit=25

And scroll to bottom of page and click the page next arrow.

It could be that the query doesn't work with a null acquisition date. Needs further investigation.

**Comment by karlcz** [comment]
This looks like a bug in the ermrestjs paging code.  It has given a
paging modifier at the end of the URL of `@after(null,1452)` when it
should be using the special null marker `@after(::null::,1452)` as per
the API documentation at
https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/data/naming.md#paging-modifiers

**Comment by robes** [comment]
@svoinea This just got fixed in chaise... do you think you could update the release to use the latest chaise?
