### ISSUE TITLE
Make the first gene or probe stand out

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#90]
When we create a specimen or an experiment we begin by selecting a gene or a probe. Those end up in a list with others we might add. We should make that first (or 'primary') gene/probe stand out if we can. Or maybe we need to unhide that field.

**Comment by svoinea** [comment]
@robes I have added on `cirm-staging` the `Probe` and `Gene` columns in the list of `visible-columns` of the `detailed` and `compact` contexts.

**Comment by robes** [comment]
Let's not. I think this adds confusion.

**Comment by svoinea** [comment]
@robes I have reverted the database changes.
