### ISSUE TITLE
add 'comments' to scans, specimens, slides, and experiments

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#91]
we can do this simply with a 'abc_comments' table. fkr to each table. markdown column for the comment, a column for the user id and for user object, and a trigger to automatically populate the user id and object columns.

**Comment by svoinea** [comment]
@robes Done through the commit e63dbb6f2cd3480f62684e45bc2ed6ad80407ff5
Available for review on `cirm-dev` and `cirm-staging`.
