### ISSUE TITLE
handle > 2 digit slide numbers

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#92]
Reported by Riana:

> I think I found a small problem when making slides that have a sequence number over 100. For example, I tried to make slide 190 for a specimen and went through and made sure that (unassigned) slide entry had been deleted from when it had been made before, but still got this message:
>
> Error 409 Conflict The request conflicts with the state of the server. Input data violates model. ERROR: duplicate key value violates unique constraint "Slide_pkey" DETAIL: Key ("ID")=(20140901-IRI_28d_1-JL-0-90-000) already exists.
>
> Deleting the (also unassigned) entry for slide 90 fixes the problem, but I don't know what would happen if we actually needed to make a slide 90 in the future. It could be that this is only a problem for those really old entries where 100+ slides were made? But anyway, I thought I'd ask in case it comes up again. There aren't many specimens where the slide count goes over 100, except for the injury study mice. It's probably only going to be an issue for those specimens, so it may not be worth worrying about. (Or maybe we already talked about this? In which case, feel free to ignore me.)

**Comment by svoinea** [comment]
@robes Currently, the last 2 digits from the `Seq.` were used in the `Slide` id, and a Revision with the constant value `000` was appended.

I have:
 - excluded the Revision from the `Slide` id
 - allow the sequence number to be up to `6` digits
 - prepend `0` to the sequence number, such that always its length in the `Slide` id will be `6`.

The changes were done through the commit c63e2652da97a192d9eef37cb0cb47cc21a38cd9

Ready for review on `cirm-dev` and `cirm-staging`.

**Comment by robes** [comment]
Sequence number of 6 digits would be overkill here. I think 3 is enough. Allows up to 999 slides from a single sample. That's more than enough.

**Comment by svoinea** [comment]
@robes In the absence of a revision number, `6` is the maximum allowance of the digits for a sequence number, such that it fits into the slide id.

I have restricted it now to `3` and appended the constant `-00` for the revision.

I have applied the change on both `cirm-dev` and `cirm-staging`.
