### ISSUE TITLE
Configure hosts to use COW snapshots of the production data volume

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#95]
The staging and dev hosts should be configured to use a copy-on-write snapshot of the master data volume. You can see the Makefiles in the synapse-{www|staging|dev} recipes as an example. It requires some coordination with Derek's people to create the snapshot of the production volume and to allow your hosts to mount them.

**Comment by svoinea** [comment]
Finalized as of 07/05/2017.

**Comment by robes** [comment]
@svoinea Well, I get `not found` for https://cirm-dev.isrd.isi.edu/hatrac/Microscopy/20160705-mKD15.5eWTSW-EAR-0-33-000/bd93d7462eebe52cac8a63ba590845474329741794bd54cc90b5e250e7740fff.czi

Shouldn't all of these be resolvable?

**Comment by svoinea** [comment]
Should work now.

I have dumped the `microscopy` and `hatrac` databases from `cirm-www` and loaded them into `cirm-dev` and `cirm-staging`.

As the COW was created on `2017/06/14`, all the scans created after that date (`229`) will not be visible on `cirm-dev` and `cirm-staging`.
