### ISSUE TITLE
Change database ownership back to `ermrest`

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/cirm-project#96]
ERMrest no longer requires the split roles of `ermrestddl` and `ermrest`. All ownership may now belong to `ermrest`.

I noticed that the catalog for cirm (at least on -dev) belongs to `ermrestddl`. Let's get this changed back to `ermrest` for simplicity moving forward.

**Comment by svoinea** [comment]
I have checked and only the tables of the `ermrest` schema had the owner `ermrestddl`.
I have changed it to `ermrest` for all the 3 `cirm` VMs.

The `ermrest_deploy` utility (that is invoked each time a VM is created and hourly by the `cirm-dev`) sets the `ermrest` ownership to the rest of the tables.
